name: commit_lint

on: [push]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Validate current commit (last commit) with commitlint
        run: |
          npm i
          npx commitlint --last --verbose
